# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      sudo apt-get -qq update
      sudo apt-get install -y libmagick++-dev
      sudo apt-get install libtiff4-dev
      sudo apt-get install libfftw3-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew reinstall imagemagick@6 --with-fontconfig --with-librsvg
      brew link --force imagemagick@6
      brew install libtiff
      brew install libtiff
      brew cask uninstall oclint
      brew install gcc
      brew link --overwrite gcc
      brew install fftw;
    fi


bioc_packages:
  - EBImage

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'

